# Generated by Django 6.0.7 on 2026-08-07 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('available_time', models.CharField(blank=True, max_length=30)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('goal', models.CharField(blank=True, max_length=30)),
                ('collaboration', models.CharField(blank=True, max_length=30)),
                ('communication', models.CharField(blank=True, max_length=30)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('one_liner', models.CharField(blank=True, max_length=100)),
                ('bio_style', models.TextField(blank=True)),
                ('bio_strength', models.TextField(blank=True)),
                ('bio_experience', models.TextField(blank=True)),
                ('bio_goal', models.TextField(blank=True)),
                ('bio_contribution', models.TextField(blank=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('open_chat', models.URLField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
