# Generated by Django 6.0.7 on 2026-08-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request', 'request'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('recommendation', 'recommendation')], max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('coffeechat-inbox', 'coffeechat-inbox'), ('coffeechat-matched', 'coffeechat-matched'), ('ai-results', 'ai-results'), ('messages', 'messages'), ('member-profile', 'member-profile')], max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
