# Generated by Django 6.0.7 on 2026-08-07 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('모집 중', '모집 중'), ('모집 마감', '모집 마감')], default='모집 중', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('color', models.CharField(default='#B8D9F5', max_length=7)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_type', models.CharField(choices=[('individual', 'individual'), ('team', 'team')], max_length=20)),
                ('status', models.CharField(default='모집 중', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='hackathons.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hackathon')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_members', models.JSONField(blank=True, default=dict)),
                ('needed_roles', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('collaboration', models.CharField(blank=True, max_length=30)),
                ('communication', models.CharField(blank=True, max_length=30)),
                ('open_chat_link', models.URLField(blank=True)),
                ('recruit_status', models.CharField(choices=[('모집 중', '모집 중'), ('매칭 완료', '매칭 완료'), ('재모집', '재모집'), ('모집 마감', '모집 마감'), ('비공개', '비공개')], default='모집 중', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hackathons.hackathon')),
            ],
            options={
                'unique_together': {('hackathon', 'creator')},
            },
        ),
    ]
