# Generated by Django 6.0.7 on 2026-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
