# Generated by Django 6.0.7 on 2026-08-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_manualparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
