apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: lylekim/my-backend:latest
          env:
            # 1. 일반 설정은 value로 직접 작성
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings"
            - name: DJANGO_DEBUG
              value: "False"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: DB_HOST
              value: "db"
            - name: DB_NAME
              value: "teambuild"
            - name: DB_USER
              value: "teambuild"

            # 2. 민감 정보는 K8s Secret에서 안전하게 불러옴
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-backend-secret    # 1단계에서 만든 K8s Secret 이름
                  key: DJANGO_SECRET_KEY         # Secret 내부 키 이름
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-backend-secret
                  key: DB_PASSWORD