apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend          # 필수: 파드를 찾기 위한 셀렉터
  template:
    metadata:
      labels:
        app: backend        # 필수: 생성될 파드의 라벨 (selector와 일치해야 함)
    spec:
      containers:
        - name: backend
          image: lylekim/my-backend:10bd7051402698a4f6d8eb342145533f8a3a753d
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings"
            - name: DJANGO_DEBUG
              value: "False"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "teambuild"
            - name: DB_USER
              value: "teambuild"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-backend-secret
                  key: DJANGO_SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-backend-secret
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000