# Generated by Django 6.0.7 on 2026-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeechat',
            name='sender_contact',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coffeechat',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='pending', max_length=11),
        ),
    ]
