# Generated by Django 6.0.7 on 2026-08-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
